language: python
python:
  - "3.4"
  - "3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "python3 setup.py install"

script:
  - "./runtests.sh"
  # Make sure the python code can at least compile
  - "python -m compileall"

after_success:
  - "cd tests"
  - "coveralls"
